version: '2'
services:
  worker:
    build: .
    links:
      - rabbitmq
      - mongodb
    depends_on:
      - rabbitmq
      - mongodb

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - 5672:5672
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/mongodb
    volumes:
      - ./data/mongodb:/data/mongodb
    ports:
      - 27017:27017