version: '2'
services:
  crawler:
    build: .
  database:
    hostname: mongo
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/mongodb
    volumes:
      - ./data/mongodb:/data/mongodb
    ports:
      - 27017:27017